export const REQUEST_METEORITE_DATA = 'REQUEST_METEORITE_DATA';
export const SUCCESS_METEORITE_DATA = 'SUCCESS_METEORITE_DATA';
export const FAILURE_METEORITE_DATA = 'FAILURE_METEORITE_DATA';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';